
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: عملیات deploy
        run: echo "اجرای عملیات deploy روی برنچ main"
