name: Deploy Nuxt 3 to GitHub Pages

permissions:
  contents: write   # allow pushing to gh-pages branch

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  # cache dependencies

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
